spring:
  application:
    name: sudal
  datasource:
    url: jdbc:postgresql://localhost:5432/sudal
    username: taek2
    password: tjdxor137!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: ../logs/sudal.log
  level:
    com.shop.sudal: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
