spring:
  application:
    name: sudal
  datasource:
    url: jdbc:postgresql://localhost:5432/sudal
    username: taek2
    password: tjdxor137!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
##  org.hibernate.type: trace

logging:
  level:
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    com.p6spy.engine.spy: DEBUG

p6spy:
  log-format: com.p6spy.engine.spy.appender.MultiLineFormat
  log-message-format: com.p6spy.engine.spy.appender.MultiLineFormat
  appender: com.p6spy.engine.spy.appender.Slf4JLogger
